# Generated by Django 6.0.2 on 2026-04-13 19:32

import rh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_vaga_solicitacao_origem_alter_candidatura_vaga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='curriculo',
            field=models.FileField(upload_to='curriculos/%Y/%m', validators=[rh.models.validar_curriculo], verbose_name='Currículo (PDF)'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('NO', 'Novo (Aguardando Triagem)'), ('EA', 'Em Análise'), ('ET', 'Em Fase de Entrevista'), ('AP', 'Aprovado (Contratado)'), ('RE', 'Reprovado / Banco de Talentos')], default='NO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pesquisademissional',
            name='setor',
            field=models.CharField(choices=[('CA', 'Comercial'), ('CO', 'Compras'), ('DI', 'Diretoria'), ('FI', 'Financeiro'), ('OB', 'Obra'), ('QA', 'SGQ'), ('FA', 'Fabrica'), ('PR', 'Projetos'), ('EG', 'Engenharia'), ('RH', 'Recursos Humanos'), ('TI', 'T.I')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitacaovaga',
            name='departamento',
            field=models.CharField(choices=[('CA', 'Comercial'), ('CO', 'Compras'), ('DI', 'Diretoria'), ('FI', 'Financeiro'), ('OB', 'Obra'), ('QA', 'SGQ'), ('FA', 'Fabrica'), ('PR', 'Projetos'), ('EG', 'Engenharia'), ('RH', 'Recursos Humanos'), ('TI', 'T.I')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='setor',
            field=models.CharField(choices=[('CA', 'Comercial'), ('CO', 'Compras'), ('DI', 'Diretoria'), ('FI', 'Financeiro'), ('OB', 'Obra'), ('QA', 'SGQ'), ('FA', 'Fabrica'), ('PR', 'Projetos'), ('EG', 'Engenharia'), ('RH', 'Recursos Humanos'), ('TI', 'T.I')], max_length=50, verbose_name='Setor'),
        ),
    ]
