# Generated by Django 6.0.2 on 2026-04-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_alter_candidatura_curriculo_alter_candidatura_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('NO', 'Novo (Aguardando Triagem)'), ('EA', 'Em Análise'), ('ET', 'Em Fase de Entrevista'), ('AP', 'Aprovado (Contratado)'), ('RE', 'Reprovado / Banco de Talentos')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='setor',
            field=models.CharField(choices=[('CA', 'Comercial'), ('CO', 'Compras'), ('DI', 'Diretoria'), ('FI', 'Financeiro'), ('OB', 'Obra'), ('QA', 'SGQ'), ('FA', 'Fabrica'), ('PR', 'Projetos'), ('EG', 'Engenharia'), ('RH', 'Recursos Humanos'), ('TI', 'T.I')], max_length=2, verbose_name='Setor'),
        ),
    ]
