# Generated by Django 6.0.2 on 2026-03-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataWarehouseCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(blank=True, max_length=20, null=True)),
                ('num_sc', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('projeto_cod', models.CharField(blank=True, max_length=50, null=True)),
                ('tarefa_cod', models.CharField(blank=True, max_length=50, null=True)),
                ('num_pedido', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_fornecedor', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('emissao_sc', models.CharField(blank=True, max_length=20, null=True)),
                ('emissao_pedido', models.CharField(blank=True, max_length=20, null=True)),
                ('data_prev_recebimento_fisico', models.CharField(blank=True, max_length=20, null=True)),
                ('data_recebimento_real', models.CharField(blank=True, max_length=20, null=True)),
                ('qtd_solicitada', models.FloatField(default=0)),
                ('qtd_pedido', models.FloatField(default=0)),
                ('qtd_recebida', models.FloatField(default=0)),
                ('valor_unitario', models.FloatField(default=0)),
                ('valor_total', models.FloatField(default=0)),
                ('leadtime_compras', models.IntegerField(default=0)),
                ('leadtime_fornecedor', models.IntegerField(default=0)),
                ('dias_atraso_entrega', models.IntegerField(default=0)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DW Compras',
                'verbose_name_plural': 'DW Compras',
            },
        ),
    ]
