# Generated by Django 4.2.30 on 2026-05-15 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualidade', '0007_remove_rnc_eficacia_pdf_rnceficaciapdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnc',
            name='categoria',
            field=models.CharField(choices=[('CO', 'Comercial'), ('PE', 'Projeto / Engenharia'), ('PC', 'PCP'), ('FA', 'Fabricação'), ('MO', 'Obra / Montagem'), ('MC', 'Montagem / Comissionamento'), ('SU', 'Suprimentos'), ('FO', 'Fornecedor Externo'), ('EX', 'Recebimento / Expedição'), ('QU', 'Qualidade'), ('RH', 'Recursos Humanos'), ('FI', 'Financeiro'), ('SG', 'SGQ'), ('PJ', 'Planejamento / Cronograma'), ('PR', 'Processo'), ('RC', 'Requisitos contratuais'), ('RN', 'Requisitos normas'), ('SI', 'Sistema')], db_index=True, default='CO', max_length=2, verbose_name='Categoria da NC'),
        ),
        migrations.AlterField(
            model_name='rnc',
            name='criticidade',
            field=models.CharField(choices=[('A', 'Alto'), ('M', 'Médio'), ('B', 'Baixo')], db_index=True, max_length=1, verbose_name='Nível de Criticidade'),
        ),
        migrations.AlterField(
            model_name='rnc',
            name='data_abertura',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='rnc',
            name='data_encerramento',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de Encerramento'),
        ),
        migrations.AlterField(
            model_name='rnc',
            name='data_prevista_conclusao',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data Prevista de Conclusão'),
        ),
        migrations.AlterField(
            model_name='rnc',
            name='detector',
            field=models.CharField(choices=[('CL', 'Cliente'), ('IN', 'Interno'), ('AI', 'Auditor Interno'), ('AE', 'Auditor Externo'), ('FO', 'Fornecedor')], db_index=True, max_length=2, verbose_name='Detector'),
        ),
        migrations.AlterField(
            model_name='rnc',
            name='origem',
            field=models.CharField(choices=[('CO', 'Comercial'), ('PE', 'Projeto / Engenharia'), ('FA', 'Fabricação'), ('MC', 'Montagem / Comissionamento'), ('SU', 'Suprimentos'), ('RH', 'RH'), ('FO', 'Fornecedor'), ('SG', 'Processo_interno_SGQ'), ('GR', 'Geral')], db_index=True, default='CO', max_length=2, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='rnc',
            name='projeto_cod',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Código do Projeto'),
        ),
        migrations.AlterField(
            model_name='rnc',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='rncs_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
        migrations.AlterField(
            model_name='rnc',
            name='status',
            field=models.CharField(choices=[('NI', 'Não iniciada'), ('EA', 'Em andamento'), ('CO', 'Concluído'), ('PR', 'Registro preliminar'), ('CA', 'Cancelado')], db_index=True, default='PR', max_length=2, verbose_name='Status'),
        ),
    ]
